### ISSUE TITLE
[Functional - MIME Error] MIME Error after loading external CSS file

### ISSUE THREAD

**Issue by KiraTodorova** [JonasunderscoreJones/McWebserver#3]
Description:

MIME Error after importing an external root.css file and call it in the index.html file.

Steps to Repro:

1. Putt he index.html in .\webserver\ folder
2. Put the root.css in .\CSS\ROOT\
3. Boot the Minecraft server
4. Observe the result

Repro rate: 5/5

Repro: 100%

Issue level: Major

Notes:
I attached the HTML and CCS File.
I play on Minecraft 1.19.2 - Fabric 0.14.22
Fabric API 0.76.0

CODEBLOCK:

index.html
`<!DOCTYPE html>
<html>
    
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Home</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="root.css">

    </head>

     <body class="body">

        <h1 class="title">STEAMVERSE - A Steampunk Modded Server</h1>

        <h2 class="title">WELCOME!</h3>

            <p>
                <button onclick="window.location.href='./HTML/DOCUMENTATION/documentation.html';" type="button" class="button">Documentation</button>
                <button onclick="window.location.href='./HTML/LIVEMAPS/liveMaps.html';" type="button" class="button">Live Maps</button>
                <button onclick="window.location.href='./HTML/CONTACT/contactKira.html';" type="button" class="button">Conact Kira</button>
                <button onclick="window.location.href='./HTML/REPORT/report.html';" type="button" class="button">REPORT ANONYMOUSL</button>
    
        </p>

        <p>

            SteamVerse is a server administrated and created by Kira T. It is about SMP and RPG. There will be machines, trains, buildings, cars, weapons, airships, all in a flatworld as the base map.

        </br>
        </br>

            You can join this server by this link:

            
            <a href="https://google.com/">INSERT DISCORD SERVER INVITE LINK</a>

        </br>
        </br>

        </p>
        
        </div>
    </div>
        
</body>

</html>`

root.css
`.body{
    
    display: flex;
    flex-direction: column;

    font-family: 'Finger Paint', cursive;
    font-size: 25px;

    color: black;

    margin: 0px;
    padding: 10px;

}

.title{

    font-family: 'Rubik Moonrocks', cursive;
    font-size: 45px;

    color: black;

    margin: 0px;
    padding: 10px;

}

.button{

    margin: 0px;
    padding: 15px;

    margin: 40px;

    border-color: white;
    background-color: rgb(0, 0, 0);
    lighting-color: white;
    color: white;

    font-family: 'Creepster', cursive;
    font-size: 18px;
    }

.maps{

    height: 720px;
    }

.googleForms{

    height: 2350px;;
}

.googleDocs1{

    height: 4000px;
    width: 1850px;
}

.googleDocs2{

    height: 10000px;
    width: 1850px;
}

.googleDocs3{

    height: 1290px;
    width: 1850px;
}

.alert-title{

    padding: 20px;
    background-color: red;
    color: white;
    text-align: center;
    font-size: large;
}

.alert-text{

    padding: 20px;
    background-color: red;
    color: white;
    text-align: center;
    font-size: large;
}
`

**Comment by JonasunderscoreJones** [comment]
You say you are putting the css file in `.css/root/` in step 2? that's an easy fix. you are supposed to put the file in the same folder as the html file since in `index.html` you are importing the css file with `<link rel="stylesheet" href="root.css">`, requesting a file called `root.css` in in the same directory as the the html file.

You can fix this by moving `root.css` into the `webserver/` folder together with the `index.html` file.

I realize that this is hard to debug since when the webserver doesn't find the file, it sends an html file (`404.html`), causing the MIME issue. I'll probably change the code to return a 404 error, in form of json or text and not html, unless an html file was requested. Thank you for bringing this up :)

The website looks like this for me:
![image](https://github.com/J-onasJones/McWebserver/assets/91549607/258f7639-cb16-4d41-bea2-410898e79815)

**Comment by KiraTodorova** [comment]
Is that the fix? OMG! Thank You!! TWT <3 <3 I will test it ASAP and reply if it's resolved or not! Cheers! <3 <3

**Comment by JonasunderscoreJones** [comment]
No worries, if the website should look the way it does in my screenshot then yeah, that's it! Let me know if it works! I am working on a way of making it easier to troubleshoot since not everyone will know the code as well as I do lol.

Btw, your server sounds amazing :)

**Comment by KiraTodorova** [comment]
Thank Chuuuuuuuu! And You would be an angelical God if You could! TWT <3 And trueeee XD I am a speed-run taught hobbyinst web developer XD

AND AWHEEEEEEEH! THANK CHUUUUUUUUU!!! TWT <3 <3 <3 <3 I will let You join once I have it run 24/7 and it's open for the public ;w; <3

**Comment by KiraTodorova** [comment]
Hewoo!!

So I have tested it, and it renders some of the stuff but it doesn't look like in Your picture.

It looks like this:

![image](https://github.com/J-onasJones/McWebserver/assets/44838454/5fb1fa31-9f35-4b87-8f6d-0dacf25e392e)


Also the MIME issue is gone but it doesn't render as for You.

Also I have the following brousers:

Chrome
Opera GX
Microsoft Edge

Also! root.css is in the same folder as index.html and it is imported like this:

`<!DOCTYPE html>
<html>
    
<head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Home</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">

        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Chelsea+Market&display=swap" rel="stylesheet">

        <link rel="stylesheet" href="root.css">

    </head>

     <body class="body">

        <h1 class="title">STEAMVERSE - A Steampunk Modded Server</h1>

        <h2 class="title">WELCOME!</h3>

            <p>
                <button onclick="window.location.href='./HTML/DOCUMENTATION/documentation.html';" type="button" class="button">Documentation</button>
                <button onclick="window.location.href='./HTML/LIVEMAPS/liveMaps.html';" type="button" class="button">Live Maps</button>
                <button onclick="window.location.href='./HTML/CONTACT/contactKira.html';" type="button" class="button">Conact Kira</button>
                <button onclick="window.location.href='./HTML/REPORT/report.html';" type="button" class="button">REPORT ANONYMOUSL</button>
    
        </p>

        <p>

            SteamVerse is a server administrated and created by Kira T. It is about SMP and RPG. There will be machines, trains, buildings, cars, weapons, airships, all in a flatworld as the base map.

        </br>
        </br>

            You can join this server by this link:

            
            <a href="https://google.com/">INSERT DISCORD SERVER INVITE LINK</a>

        </br>
        </br>

        </p>
        
        </div>
    </div>
        
</body>

</html>`

**Comment by JonasunderscoreJones** [comment]
I used firefox for the screenshot above. Using Chrome I get the following result:

![image](https://github.com/J-onasJones/McWebserver/assets/91549607/22017234-af48-4049-8f91-39940949340d)

I think there might be an issue with your fonts and how they render in different Browsers since for me it isn't rendering the font at all? This doesn't change when I just open the html file in Chrome so it's something with your css. you might want to check if some of the fonts don't work. What am I supposed to see? is my first screenshot of Firefox the correct way? the only difference between that and your screenshot is the font and that you're using a dark mode extension I assume. Do you get any difference between when you open the html file and when you use the server link?

**Comment by KiraTodorova** [comment]
Heyyoooooo!!

So the first pictures You sent are the right fonts that this document should look like.

So the issue of Chrome not rendering Google's fonts is dumb af XD But I know the issue and its solution, so You were right! Am so so so so so sorry T.T <3

So for everyone who doesn't know the solution follow this tutorial:

https://stackoverflow.com/questions/22011139/google-fonts-are-not-rendering-on-google-chrome/22025804#22025804

"remove the 'http:' in:

<link href='http://fonts.googleapis.com/css?family=Alfa+Slab+One' rel='stylesheet' type='text/css'> "

That should do the trick!

Also the funny part is that Google gives You the https link inside the Google Font website but they didn't think that ppl may use Chrome when doing google stuff XD \_(O.O???)_/

Also thank You so much for EVERYTHING and again ,am sowwy T.T <3

**Comment by JonasunderscoreJones** [comment]
No worries, glad I could help :)

Yes, the fact that some google fonts don't render in google chrome is ironic but I have to say I'm not surprised, I've had many issues with google fonts in the past. your safest bet is to download the font in form of a `.ttf` file (which is possible on the google fonts website) and import those into your CSS code locally without the link to google fonts. this should work in 100% of cases (I think). I tested it and it also works with my mod without any necessary updates!

**Comment by KiraTodorova** [comment]
Ooooooooh! AMAZIIIIIIIIIIIING!!! Thank Chu thank Chu! TwT

And yeah it's very stupid ngl XD

Anyways, ma fix didn't do crap O.O So am gonna do the .trf one XD <3 <3

I'll tell how it goes uwu <3

**Comment by KiraTodorova** [comment]
HOOORAAAAAAAAAAAAAAAY!!! IT WORKS WITH .ttf font files! YOU ARE THE BEEEEEEEEST! TWT <3 <3 <3

Thank Chuuuuuuuuuuuuuuuuuuuuuuuu! TWT <3 <3 <3

**Comment by JonasunderscoreJones** [comment]
Sweet! I'm currently writing a wiki at https://github.com/J-onasJones/McWebserver/wiki/ to make it easier for anyone to setup their server and I'll add a few examples so that mistakes such as your's don't happen again! I'm also working on a way of displaying server information on the website such as player list and much more so stay tuned for that if you're interested :)

**Comment by KiraTodorova** [comment]
OMG that is great and I sure will! Thank You so much for this amazing sneak peek! I am def. excited! ^w^ <3 <3
